"""001_initial_enterprise_schema

Revision ID: 1399febe2a23
Revises: 
Create Date: 2026-09-23 23:30:07.808358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1399febe2a23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_analyses_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_analyses_workspace_id_workspaces', 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('storage_backend', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_datasets_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key('fk_datasets_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_experiments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key('fk_experiments_workspace_id_workspaces', 'workspaces', ['workspace_id'], ['id'])
        batch_op.create_foreign_key('fk_experiments_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_reports_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key('fk_reports_workspace_id_workspaces', 'workspaces', ['workspace_id'], ['id'])
        batch_op.create_foreign_key('fk_reports_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_workspace_id'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_reports_workspace_id_workspaces', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_reports_is_deleted'))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_experiments_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_experiments_workspace_id_workspaces', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_experiments_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_experiments_is_deleted'))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_datasets_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_datasets_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_is_deleted'))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('storage_backend')
        batch_op.drop_column('storage_key')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_analyses_workspace_id_workspaces', type_='foreignkey')
        batch_op.drop_constraint('fk_analyses_created_by_user_id_users', type_='foreignkey')

    # ### end Alembic commands ###
